In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split    
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
# Data Preparation
age = np.array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

df = pd.DataFrame({'Age': age})
df.head(2)

   Age
0   18
1   19

In [ ]:
# col standarization - 
# You can use library or you can implement by yourself
mean = df['Age'].mean()
std = df['Age'].std()
df['Age'] = (df['Age'] - mean) / std
df.head(2)

df.head(2)
# before applying KNN algorithm - this is important
# why? because KNN is sensitive to the scale of the data

        Age
0 -1.540658
1 -1.283881

In [10]:
from sklearn.datasets import load_iris
iris = load_iris()
# Convert to DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target
df.head(2)

# rename it
df.rename(columns={'sepal length (cm)': 'sepal_length', 
                   'sepal width (cm)': 'sepal_width', 
                   'petal length (cm)': 'petal_length', 
                   'petal width (cm)': 'petal_width'}, inplace=True)


df.head(2)

# train test split

X_train, X_test, y_train, y_test = train_test_split(df.drop('target', axis=1), df['target'], test_size=0.2, random_state=42)

In [14]:
# lets train the model with one parameter and then note the accuracy and repeate for all
features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
accuracy = {}
for feature in features:
    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(X_train[[feature]], y_train)
    y_pred = knn.predict(X_test[[feature]])
    accuracy[feature] = accuracy_score(y_test, y_pred)

# combine feature with best with all feature to know which combination will have the best accuracy
best_features = sorted(accuracy, key=accuracy.get, reverse=True)
print("Best feature:", best_features[0])
for feature in features:
    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(X_train[best_features + [feature]], y_train)
    y_pred = knn.predict(X_test[best_features + [feature]])
    accuracy[f"best + {feature}"] = accuracy_score(y_test, y_pred)

Best feature: petal_width

In [16]:
# conclusion - The best feature for classification 
# is the one that provides the highest accuracy when used alone. 
# However, combining it with other features may yield even better results. 
# The KNN model's performance can vary significantly based on the choice of features,
#  highlighting the importance of feature selection in machine learning.
# since there is no direct way to get the feature importance in KNN,
# we rely on accuracy scores to gauge the effectiveness of each feature.
# can we say KNN is blackbox model or not?
# Yes, KNN can be considered a black box model to some extent.
# While we can observe the impact of different features on the model's accuracy, ( very important question for interview)
# the internal decision-making process of the KNN algorithm is not easily interpretable.

In [ ]:
# onehotencoding
data = {
    'gender': ['male', 'female', 'female', 'male'],
    'age': [25, 30, 22, 35],
    'income': [50000, 60000, 45000, 80000]
}

df = pd.DataFrame(data)

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_features = encoder.fit_transform(df[['gender']])
encoded_features.toarray()

# you can map to your df
df_encoded = df.copy()
df_encoded[encoder.get_feature_names_out()] = encoded_features.toarray()
df_encoded.head(2)
# you can drop the original categorical columns
df_encoded = df_encoded.drop(columns=['gender'])
df_encoded.head(2)

# issue with onehotencoding?
# dimensionality explosion
# when you have many categories, the feature space can become very large
# this can lead to increased computational cost and potential overfitting

# what we can do ??
# 1. Use Target Encoding (link : https://www.kaggle.com/code/abhishekkrthakur/target-encoding)
# 2. Use Feature Hashing (link : https://www.kaggle.com/code/abhishekkrthakur/feature-hashing)
# 3. Use Dimensionality Reduction Techniques using PCA (link : https://www.kaggle.com/code/abhishekkrthakur/pca)

   age  income  gender_female  gender_male
0   25   50000            0.0          1.0
1   30   60000            1.0          0.0